import hlt

RANGE_OF_AGGRESSION = hlt.constants.MAX_SPEED * 3
UNDOCK_IF_PLANET_DEPLETED = True
RUSH_DETECT_DURATION = 16
RUSH_DETECT_RANGE_DUEL = 12
RUSH_DETECT_RANGE_FFA = 10
RUSH_READY_RADIUS = 3
GREEDY_PLANET_DISTANCE = hlt.constants.MAX_SPEED * 3
